development:
  adapter: postgresql
  encoding: unicode
  database: sweat_bet_development
  pool: 5
  username: RbyWoo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sweat_bet_test
  pool: 5
  username: RbyWoo
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sweat_bet_development
  pool: 5
  username: RbyWoo-
  password:
